#!/bin/bash
#Conexão do banco de dados
#export DATABASE_URL = 'postgres://foo:bar@localhost:5432/db'

export DATABASE_URL='postgres://root:root@localhost:5432/websites_manager'

/opt/projetos/sitesmanager/bin/python /opt/projetos/sitesmanager/websites_manager/manage.py syncdb

