# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePathModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('path_root', models.CharField(max_length=255, verbose_name='Pasta raiz')),
                ('path_url', models.CharField(max_length=255, verbose_name='URL raiz')),
            ],
            options={
                'verbose_name': 'Pasta de arquivo',
                'verbose_name_plural': 'Pasta de arquivos',
            },
        ),
    ]
